FROM python:3.12

ARG SCRIPT
ENV SCRIPT $SCRIPT

WORKDIR /app

COPY /requirements_refactor.txt /app


RUN cat requirements_refactor.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements_refactor.txt
RUN pip freeze > /var/log/requirements_installation.log
RUN cat /var/log/requirements_installation.log
COPY /src/. src/.

WORKDIR /app/src/


CMD ["sh", "-c", "uvicorn $SCRIPT --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips '*'"]