FROM python:3.9

WORKDIR /app
COPY deployment/requirements_dev.txt /app/requirements_dev.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements_dev.txt

COPY deployment/src/. /app/src/.

WORKDIR /app/src/

CMD ["sh", "-c", "uvicorn your_script:app --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips '*'"]
